chembl_smiles_url: https://github.com/unmtransinfo/Badapple2-API/blob/main/benchmark/data/chembl_smiles.csv.gz
chembl_smiles_gz_file: data/chembl_smiles.csv.gz
chembl_smiles_csv_file: data/chembl_smiles.csv
